FROM apache/airflow:2.8.0-python3.8

# INSTALL PYTHON REQUIREMENTS
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# AIRFLOW CONFIGURATION
ENV AIRFLOW__CORE__EXECUTOR=CeleryExecutor
ENV AIRFLOW__CORE__FERNET_KEY=''
ENV AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION='true'
ENV AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=3
ENV AIRFLOW__CORE__PARALLELISM=4
ENV AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=2
ENV AIRFLOW__CORE__LOAD_EXAMPLES='false'

ENV AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
ENV AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/0

ENV AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Jakarta
ENV AIRFLOW__WEBSERVER__EXPOSE_CONFIG='true'

ENV AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
ENV AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=30
ENV AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=120
ENV AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK='true'

ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

ENV AIRFLOW__API__AUTH_BACKENDS='airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'